---
output: github_document
editor_options: 
  markdown: 
    wrap: 72
---

# HighDimenCDM: High-Dimensional Cognitive Diagnosis Models

To cite this paper:

- Ma, W., Wang, K., & Xu, G. (Accepted). Parameter estimation of
  cognitive diagnosis models with stochastic EM algorithm.
  Behaviormetrika.

- Mei, Y., Ma, W., Wang, K., & Xu, G. (2026) HighDimenCDM:
  High-Dimensional Cognitive Diagnosis Models. R package.

## Features

This package aims to provide tools for high-dimensional cognitive
diagnosis models. Currently, it supports the following features:

- Implements stochastic expectation-maximization algorithms for
  high-dimensional cognitive diagnosis models

- Efficient Gibbs sampling for attribute estimation

- Supports binary response cognitive diagnosis models with binary
  attributes

## Installation

Install the development version of **HighDimenCDM** from GitHub using
the `devtools` package.

```{r gh-installation, eval = FALSE}
# install.packages("devtools")
#devtools::install_github("HighDimenCDM")
```
