// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// seqGibbs
arma::umat seqGibbs(arma::umat& alpha, const arma::mat& Q, const arma::mat& ip, const arma::mat& data, const arma::field<arma::umat>& rp);
RcppExport SEXP _stEM3_seqGibbs(SEXP alphaSEXP, SEXP QSEXP, SEXP ipSEXP, SEXP dataSEXP, SEXP rpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::umat& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ip(ipSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::umat>& >::type rp(rpSEXP);
    rcpp_result_gen = Rcpp::wrap(seqGibbs(alpha, Q, ip, data, rp));
    return rcpp_result_gen;
END_RCPP
}
// seqGibbs2
void seqGibbs2(arma::umat& alpha, const arma::mat& Q, const arma::mat& ip, const arma::mat& data, const arma::field<arma::umat>& rp);
RcppExport SEXP _stEM3_seqGibbs2(SEXP alphaSEXP, SEXP QSEXP, SEXP ipSEXP, SEXP dataSEXP, SEXP rpSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::umat& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ip(ipSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::umat>& >::type rp(rpSEXP);
    seqGibbs2(alpha, Q, ip, data, rp);
    return R_NilValue;
END_RCPP
}
// aggregatebyCol
arma::mat aggregatebyCol(arma::mat& x, arma::vec g);
RcppExport SEXP _stEM3_aggregatebyCol(SEXP xSEXP, SEXP gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type g(gSEXP);
    rcpp_result_gen = Rcpp::wrap(aggregatebyCol(x, g));
    return rcpp_result_gen;
END_RCPP
}
// inplaceadd
void inplaceadd(arma::mat& x);
RcppExport SEXP _stEM3_inplaceadd(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    inplaceadd(x);
    return R_NilValue;
END_RCPP
}
// fieldtest
arma::mat fieldtest(arma::field<arma::mat>& x);
RcppExport SEXP _stEM3_fieldtest(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::mat>& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(fieldtest(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_stEM3_seqGibbs", (DL_FUNC) &_stEM3_seqGibbs, 5},
    {"_stEM3_seqGibbs2", (DL_FUNC) &_stEM3_seqGibbs2, 5},
    {"_stEM3_aggregatebyCol", (DL_FUNC) &_stEM3_aggregatebyCol, 2},
    {"_stEM3_inplaceadd", (DL_FUNC) &_stEM3_inplaceadd, 1},
    {"_stEM3_fieldtest", (DL_FUNC) &_stEM3_fieldtest, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_stEM3(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
