# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

seqGibbs <- function(alpha, Q, ip, data, rp) {
    .Call(`_stEM3_seqGibbs`, alpha, Q, ip, data, rp)
}

seqGibbs2 <- function(alpha, Q, ip, data, rp) {
    invisible(.Call(`_stEM3_seqGibbs2`, alpha, Q, ip, data, rp))
}

aggregatebyCol <- function(x, g) {
    .Call(`_stEM3_aggregatebyCol`, x, g)
}

inplaceadd <- function(x) {
    invisible(.Call(`_stEM3_inplaceadd`, x))
}

fieldtest <- function(x) {
    .Call(`_stEM3_fieldtest`, x)
}

